apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex6-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex6-php
  template:
    metadata:
      labels:
        app: ex6-php
    spec:
      containers:
        - name: ex6-php
          image: acrecdemo51426.azurecr.io/ex6-php:1.1
          ports:
            - containerPort: 80
          env:
            - name: APP_VERSION
              value: "1.1.0"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /version.php
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /version.php
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ex6-php
spec:
  type: LoadBalancer
  selector:
    app: ex6-php
  ports:
    - port: 80
      targetPort: 80
